### ISSUE TITLE
LMDB

### ISSUE THREAD

**Issue by farooqkz** [alirezaahani/cherrypy-site#1]
You might find LMDB interesting(it is a database)

**Comment by alirezaahani** [comment]
Thank for the suggestion.
I have a plan for changing the database,  but this code is the first code I used databases in it. 
I may switch to mysql or other SQL databases.

**Comment by farooqkz** [comment]
How about NoSQL ones?

**Comment by alirezaahani** [comment]
Hm... I'm not sure about them,  if I switch to nosql ones I have to change a lot of functions to work with that database right?

**Comment by farooqkz** [comment]
If you switch to any DB which is not SQLite you have to change those functions. but not "a lot". See how LMDB works or some other nosql databases. You might like them. LMDB, unlike SQLite does not have a separate language to work with database.

**Comment by alirezaahani** [comment]
I will think about it ...
