### ISSUE TITLE
Use 4 spaces for indenting

### ISSUE THREAD

**Issue by farooqkz** [alirezaahani/cherrypy-site#2]
As standards say

**Comment by alirezaahani** [comment]
Thanks,  is there any fast way for changing tab to space in a 202 line file?

**Comment by farooqkz** [comment]
Depends on your editor.
An editor independent way is using "sed".

**Comment by alirezaahani** [comment]
Oh I forgot about set,  I will take care of it soon,  but right now I'm so busy at life

**Comment by alirezaahani** [comment]
Thanks again for reporting , it's now fixed.

**Comment by farooqkz** [comment]
Very good :)
