### ISSUE TITLE
Use SHA instead of MD5

### ISSUE THREAD

**Issue by farooqkz** [alirezaahani/cherrypy-site#3]
As MD5 is too weak!

**Comment by alirezaahani** [comment]
Thanks,  but I'm busy at life right now, I will change it soon.(unfortunately I have to remove all the accounts)

**Comment by alirezaahani** [comment]
Is sha256 safe enough ?

**Comment by farooqkz** [comment]
I think it is but you'd better use your fav search engine not me. They are much wiser than me!

**Comment by alirezaahani** [comment]
I'm using sha512 right now. Thanks for your report
