### ISSUE TITLE
Master...

### ISSUE THREAD

**Issue by farooqkz** [alirezaahani/cherrypy-site#4]
Soon I shall call you "master"... and:
![master](https://user-images.githubusercontent.com/15038218/87460220-be785900-c621-11ea-915e-89aee25e03ea.jpg)

**Comment by bsimjoo** [comment]
-_-

**Comment by farooqkz** [comment]
I am serious!
If this boy continue like this, one day he'll become my new master...

**Comment by alirezaahani** [comment]
Thanks farooq.This massage scared me a lot XD because when I saw it in my inbox,  was like this : "aww man,  did I massed up again in github ?".
And thanks again for your support :)
+ Can I close this issue ?

**Comment by farooqkz** [comment]
No wait for about a day or two I want to see other people's comments :)

**Comment by alirezaahani** [comment]
Okay :)
