### ISSUE TITLE
Use captcha for login and signup

### ISSUE THREAD

**Issue by farooqkz** [alirezaahani/cherrypy-site#5]
This way someone would not be able to do brute force. This also prevents attacks on login and signup process such as DoS.
+ Do you want an account on LispShell? You can run servers there(but on non-standard ports) and cherrypy is installed globally.

**Comment by alirezaahani** [comment]
> This way someone would not be able to do brute force. This also prevents attacks on login and signup process such as DoS.
> 
>     * Do you want an account on LispShell? You can run servers there(but on non-standard ports) and cherrypy is installed globally.

Thank you for the important point you made.I will work on it and add it soon.
 
*And about LispShell, How can I contact with you about it ?

**Comment by alirezaahani** [comment]
Fixed but I will leave it open if someone wants to say anything about captcha

**Comment by farooqkz** [comment]
Excellent :)
