### ISSUE TITLE
Suggesting new architecture for your web application

### ISSUE THREAD

**Issue by farooqkz** [alirezaahani/cherrypy-site#6]
This is just a suggestion and even if you don't agree I might do it alone.
The goal is a pretty simple but working and useful Persian social media which is **private**.
After registering process, each user may create a new group or join an existing one or both.
The one who has created a group will become admin of that group and they may make their group public(anyone can join without confirmation) or private(anyone who wants to join MUST get confirmation from group admin).
In each group users may create threads or post comments on existing threads. The admin of groups as well as the admin(s) of the entire network may delete or edit posts. Each post may have from 1 to 3 attachment(s) of file(s) of any kind and share them with others.
Users are also able to send posts(with or without attachments) directly to other users.
Also as it is a **private** social media, there might exist a "master key" for the entire site.

**Comment by alirezaahani** [comment]
This app is opensource and free you can do what ever you want with it,about your idea,  I started this app just for fun and learning. Right now I can not code much. You can start it your self and if you need any help I will help you.I like your idea but I can't start a another app right now.

**Comment by farooqkz** [comment]
okay :)

**Comment by farooqkz** [comment]
@alirezaahani I've found matrix.org and self hosted it. No need to implement what I said anymore :)
